chapter: 17

page_headers:
  - "CHAPTER 17"
  - "RESPIRATORY CONDITIONS"

strip_page_labels_regex: "^\\d{1,2}\\.\\d{1,2}$"

numeric_topics:
  "17.1": "CONDITIONS WITH PREDOMINANT WHEEZE"
  "17.1.1": "ACUTE ASTHMA & ACUTE EXACERBATION OF COPD, ADULTS"
  "17.1.2": "ACUTE ASTHMA, CHILDREN"
  "17.1.3": "CHRONIC ASTHMA"
  "17.1.4": "ACUTE BRONCHIOLITIS IN CHILDREN"
  "17.1.5": "CHRONIC OBSTRUCTIVE PULMONARY DISEASE (COPD)"

  "17.2": "STRIDOR (UPPER AIRWAYS OBSTRUCTION)"
  "17.2.1": "CROUP (LARYNGOTRACHEO BRONCHITIS) IN CHILDREN"

  "17.3": "RESPIRATORY INFECTIONS"
  "17.3.1": "INFLUENZA"
  "17.3.2": "ACUTE BRONCHITIS IN ADULTS OR ADOLESCENTS"
  "17.3.3": "ACUTE EXACERBATION OF CHRONIC OBSTRUCTIVE PULMONARY DISEASE (COPD)"
  "17.3.4": "PNEUMONIA"
  "17.3.4.1": "PNEUMONIA IN CHILDREN"
  "17.3.4.2": "PNEUMONIA IN ADULTS"
  "17.3.4.2.1": "UNCOMPLICATED PNEUMONIA"
  "17.3.4.2.2": "PNEUMONIA IN ADULTS WITH UNDERLYING MEDICAL CONDITIONS OR >65 YEARS OF AGE"
  "17.3.4.2.3": "SEVERE PNEUMONIA"
  "17.3.4.2.4": "PNEUMOCYSTIS PNEUMONIA"

  "17.4": "PULMONARY TUBERCULOSIS (TB)"
  "17.4.1": "PULMONARY TUBERCULOSIS (TB) IN ADULTS"
  "17.4.1.1": "TB CHEMOPROPHYLAXIS/ISONIAZID PREVENTIVE THERAPY (IPT) IN ADULTS"
  "17.4.1.2": "TB CONTROL PROGRAMME: MEDICINE REGIMENS IN ADULTS"
  "17.4.2": "PULMONARY TUBERCULOSIS (TB) IN CHILDREN"
  "17.4.2.1": "TB CHEMOPROPHYLAXIS/ISONIAZID PREVENTIVE THERAPY (IPT) IN CHILDREN"
  "17.4.2.2": "TB CONTROL PROGRAMME: MEDICINE REGIMENS IN CHILDREN"
  "17.4.3": "TB, HIV AND AIDS"
  "17.4.4": "DRUG-RESISTANT TUBERCULOSIS (MDR TB)"
  "17.4.4.1": "ISONIAZID MONO-RESISTANT TUBERCULOSIS IN ADULTS"
  "17.4.4.2": "RIFAMPICIN-RESISTANT TUBERCULOSIS (RR TB), IN ADULTS"
  "17.4.4.3": "RIFAMPICIN-RESISTANT (RR), PRE-XDR AND XDR TUBERCULOSIS, IN CHILDREN"

logical_headings:
  - "DESCRIPTION"
  - "GENERAL MEASURES"
  - "MEDICINE TREATMENT"
  - "REFERRAL"
  - "DIAGNOSIS"
  - "INVESTIGATIONS"
  - "DISPOSITION"
